# Site settings
title: 'CodeIsc'
description: 'CodeIsc'
keyword: 'code, isc, codeisc'
url: 'http://blog.codeisc.com'

# if you don't need baseurl, you should leave this value blank.
baseurl: ''

# Navigation links
nav:
  tags: '/tags.html'

# Author
author: 'Ivan Sanz'
nickname: 'ivansanz'
bio: 'C++/.NET engineer'
avatar: '/assets/img/ivansanz.png'

# Analytics
analytics: true
analytics-gtag: UA-111742878-1

# Search
search: false

# Night mode
nightMode: false

# Comments
disqus: true
disqus_url: '//codeisc.disqus.com/embed.js'

# Share
social-share: true
social-share-items: ['twitter', 'facebook', 'google', 'linkedin']

# theme color
theme-color: 'default'  # pink or default

# Post header background patterns (when the post no cover): circuitBoard, overlappingCircles, food, glamorous, ticTacToe, seaOfClouds
postPatterns: 'circuitBoard'

# SNS settings, url: weibo, zhihu, twitter, instagram, juejin, github, douban, facebook, dribble, uicn, jianshu, medium, linkedin
sns:
  linkedin: '//linkedin.com/in/ivan-sanz-carasa'
  github: '//github.com/isc30'
  email: 'mailto:ivansanzcarasa@gmail.com'

# Tags
recommend-tags: true # whether or not display recommend-tags on the sidebar
recommend-condition-size: 1 # a tag will be recommended if the size of it is more than this value

# Build settings
paginate: 6
paginate_path: 'page:num'
exclude: ['node_modules', 'dev', 'package.json', 'gulpfile.js', '.gitignore', 'README.md']

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true

excerpt_separator: <!-- more -->
    
# Plugins
plugins: [jekyll-paginate]
