version: '3'

services:
  site:
    image: jekyll/jekyll:3.8.6
    command: jekyll serve --livereload --verbose --force_polling
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle
